[package]
name = "ops4struct"
version = "0.1.0"
authors = ["Sergey Chernomorets <s.chernomorets@gmail.com>"]
edition = "2018"

[dependencies]
ops4struct_derive = { path = "ops4struct_derive" }


[workspace]
members = [
	"ops4struct_derive"
]

